% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name untitled
%  @associatedFile /MATLAB Drive/untitled.m
%  @mostRecentlyActioned true
%  @uniqueId C441D518

untitled

%% @name equation_how
%  @associatedFile /MATLAB Drive/equation_how.m
%  @mostRecentlyActioned true
%  @uniqueId 20A82312

equation_how

